
name: CICD
on:
  workflow_dispatch: null
jobs:
  restore: restore code
  steps:
    - name: checkout code
      run: echo "clone code"
  build:
    steps:
      - name: build code
        run: echo "build code"
  test:
    steps:
      - name: test code
        run: echo "test code"
  deploy:
    steps:
      - name: deploy code
        run: echo "deploy code"
