name: Hello 
on:
   push:
     branches:
       - main    
jobs:
  greet:
    runs-on: ubuntu-latest
    
    steps:
     - name:  say hello to users
       run: echo "hello from kaustubh"

     - name: say hello to username
       run: echo "Hello $USER"
       
  show-versions:
    runs-on: ubuntu-latest
    steps:
      - name: docker and python version
        run: docker --version && python --version
       

      
    
  
